name: cnss_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.0
  provider: ^6.1.2
  sqflite: ^2.3.3
  flutter_vector_icons: ^2.0.0
  uuid: ^4.4.0
  fl_chart: ^0.68.0
  pdf: ^3.10.8
  printing: ^5.12.0
  
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.6.1
  month_year_picker: ^0.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite_common_ffi_web: ^0.4.3+1
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/